# Generated by Django 4.2.11 on 2024-04-09 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(max_length=50)),
                ('user_lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_permission', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('LINEMANAGER', 'Line Manager'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'user_account',
                'ordering': ['user_lastname', 'user_firstname'],
                'unique_together': {('user_firstname', 'email')},
            },
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('account_number', models.CharField(max_length=8)),
                ('sort_code', models.CharField(max_length=8)),
                ('tax_code', models.CharField(max_length=100)),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFormModel',
            fields=[
                ('claimID', models.AutoField(primary_key=True, serialize=False)),
                ('lineManagerID', models.CharField(max_length=100)),
                ('dateMade', models.DateField()),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=100)),
                ('typeClaim', models.CharField(choices=[('TRAVEL', 'travel'), ('MEAL', 'meal'), ('NIGHTSTAY', 'night stay'), ('GIFT', 'gift')], default='meal', max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('acknowledgement', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('PENDING', 'pending'), ('PROCESSED', 'processed'), ('REJECTEDF', 'rejectedbyfinance')], default='PENDING', max_length=20)),
                ('dateApproved', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
