# Generated by Django 5.0.4 on 2024-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeformmodel',
            name='approvedBy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
