# Generated by Django 3.2.25 on 2024-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='flagged_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
