# Generated by Django 4.2.11 on 2024-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeformmodel',
            name='comments',
            field=models.CharField(default='', max_length=100),
        ),
    ]
