# Generated by Django 4.2.11 on 2024-04-10 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='flagged_password_change',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='dateMade',
            field=models.DateField(default=datetime.date(2024, 4, 10)),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='lineManagerID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='receipt',
            field=models.ImageField(null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='typeClaim',
            field=models.CharField(choices=[('TRAVEL', 'travel'), ('MEAL', 'meal'), ('NIGHTSTAY', 'night stay'), ('GIFT', 'gift'), ('OTHER', 'other')], default='meal', max_length=20),
        ),
    ]
