# Generated by Django 4.2.11 on 2024-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('typeClaim', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('acknowledgement', models.BinaryField()),
            ],
        ),
    ]
