# Generated by Django 4.2.11 on 2024-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employeeformmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfomodel',
            name='country',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfomodel',
            name='zip_code',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
