# Generated by Django 4.2.11 on 2024-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeformmodel',
            name='acknowledgement',
            field=models.BooleanField(),
        ),
    ]
