# Generated by Django 4.2.11 on 2024-04-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employeeformmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeformmodel',
            name='dateApproved',
            field=models.DateField(default="2024-04-08"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='dateMade',
            field=models.DateField(default="2024-04-08"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
