# Generated by Django 4.2.11 on 2024-04-11 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeformmodel_approvedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeformmodel',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='userinfomodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfomodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfomodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='flagged_password_change',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='claimedBy',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='currency',
            field=models.CharField(choices=[('GBP', '£'), ('USD', '$'), ('EUR', '€'), ('JPY', '¥'), ('MXN', '₱'), ('INR', '₹'), ('CHF', '₣')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='dateMade',
            field=models.DateField(default=datetime.date(2024, 4, 11)),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='lineManagerID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='receipt',
            field=models.ImageField(null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='typeClaim',
            field=models.CharField(choices=[('TRAVEL', 'travel'), ('MEAL', 'meal'), ('NIGHTSTAY', 'night stay'), ('GIFT', 'gift'), ('OTHER', 'other')], default='meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='manager_id',
            field=models.IntegerField(null=True),
        ),
    ]
