# Generated by Django 4.2.11 on 2024-04-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeeformmodel_acknowledgement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeformmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='claimID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='lineManagerID',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='userID',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='typeClaim',
            field=models.CharField(choices=[('TRAVEL', 'travel'), ('MEAL', 'meal'), ('NIGHTSTAY', 'night stay'), ('GIFT', 'gift')], default='meal', max_length=20),
        ),
    ]
