# Generated by Django 5.0.3 on 2024-04-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinfomodel_city_userinfomodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
