# Generated by Django 5.0.4 on 2024-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employeeformmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('account_number', models.CharField(max_length=8)),
                ('sort_code', models.CharField(max_length=8)),
                ('tax_code', models.CharField(max_length=100)),
                ('manager_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
