# Generated by Django 4.2.11 on 2024-04-07 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
            ],
        ),
        migrations.AlterField(
            model_name='employeeformmodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='receipt',
            field=models.ManyToManyField(default='path/to/image.png', to='accounts.vatreceipt'),
        ),
    ]
