# Generated by Django 5.0.3 on 2024-04-07 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userinfomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeformmodel',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='userinfomodel',
            name='userID',
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfomodel',
            name='user_id',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
