
# Generated by Django 5.0.4 on 2024-04-07 18:37


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeformmodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
