# Generated by Django 4.2.11 on 2024-04-07 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employeeformmodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeformmodel',
            name='userID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
