# Generated by Django 5.0.3 on 2024-04-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employeeformmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeformmodel',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('PENDING', 'pending'), ('PROCESSED', 'processed'), ('REJECTEDF', 'rejectedbyfinance')], default='PENDING', max_length=20),
        ),
    ]
