# Generated by Django 4.2.11 on 2024-04-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employeeformmodel_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeformmodel',
            name='userID',
        ),
    ]
