# Generated by Django 4.2.11 on 2024-04-07 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_employeeformmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeformmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
