# Generated by Django 4.2.11 on 2024-04-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_employeeformmodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeformmodel',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='VATReceipt',
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
