# Generated by Django 4.2.11 on 2024-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_employeeformmodel_receipt_delete_vatreceipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeformmodel',
            name='lineManagerID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
