# Generated by Django 4.2.11 on 2024-04-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_employeeformmodel_linemanagerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeformmodel',
            name='receipt',
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='receipt',
            field=models.ManyToManyField(to='accounts.receipt'),
        ),
    ]
