# Generated by Django 4.2.11 on 2024-04-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_receipt_remove_employeeformmodel_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeformmodel',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AddField(
            model_name='employeeformmodel',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
